<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmallBankingSystem.Application\SmallBankingSystem.Application.csproj" />
    <ProjectReference Include="..\SmallBankingSystem.Domain\SmallBankingSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24" />
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.24" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ProjectDesign">
      <HintPath>..\..\ProjectDesign\bin\Debug\ProjectDesign.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
